import './globals.css'
import { Inter } from 'next/font/google';

import Navigator from './component/Navigator';
import Header from './component/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className + ' grid'}>
        <Navigator></Navigator>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
